name: Demos

on:
  pull_request: {}
  push:
    branches:
    - main
  workflow_dispatch: {}

env:
  INSTALL_RUST_VERSION: "1.75"

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Install Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          default: true
          profile: minimal
          toolchain: ${{ env.INSTALL_RUST_VERSION }}

      - name: Use Rust Cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Build Rust Demo
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1
        with:
          args: -p juicebox_demo_cli
          command: build

      - name: Software Realm
        id: software-realm
        uses: ./.github/actions/software-realm
        with:
          start-realm-count: 25

      - name: Run Rust Demo
        run: target/debug/demo --configuration ${{ steps.software-realm.outputs.configuration }} --auth-tokens ${{ steps.software-realm.outputs.auth-tokens }}

  swift:
    name: Swift
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Install Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          default: true
          profile: minimal
          toolchain: ${{ env.INSTALL_RUST_VERSION }}

      - name: Use Rust Cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Build FFI
        run: swift/ffi.sh

      - name: Use Swift Cache
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
        with:
          path: swift/demo/.build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build Swift Demo
        run: cd swift/demo && swift build --verbose

      - name: Software Realm
        id: software-realm
        uses: ./.github/actions/software-realm
        with:
          start-realm-count: 25

      - name: Run Swift Demo
        run: swift/demo/.build/debug/demo -c ${{ steps.software-realm.outputs.configuration }} -a ${{ steps.software-realm.outputs.auth-tokens }}

  wasm:
    name: WASM
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Install Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          default: true
          profile: minimal
          toolchain: ${{ env.INSTALL_RUST_VERSION }}

      - name: Use Rust Cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          # it's not possible to pin certs yet with the experimental fetch in node 18,
          # and our polyfill doesn't work well in 18. stick with 16 for now.
          node-version: 16

      - uses: jetli/wasm-pack-action@0d096b08b4e5a7de8c28de67e11e945404e9eefa # v0.4.0

      - name: Build WASM
        run: wasm-pack build rust/sdk/bridge/wasm --out-dir ../../../../javascript/juicebox-sdk --out-name juicebox-sdk --target nodejs

      - name: NPM Install
        run: |
          cd javascript/demo
          npm install
          npm install -g ts-node

      - name: Software Realm
        id: software-realm
        uses: ./.github/actions/software-realm
        with:
          start-realm-count: 25

      - name: Run WASM Demo
        run: javascript/demo/demo.ts -c ${{ steps.software-realm.outputs.configuration }} -a ${{ steps.software-realm.outputs.auth-tokens }}
